
services:
  redis:
    image: redis:latest
    restart: always
    container_name: redis
    ports:
      - 6379:6379
  
  mongo:
    image: mongo:latest
    restart: always
    container_name: mongo
    ports:
      - 27017:27017
  
  urlshortener:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: urlshortener
    ports:
      - 7575:7575
      - 7576:7576
    depends_on:
      - redis
      - mongo
    environment:
      ASPNETCORE_HTTP_PORT: "https://+:7575"
      ASPNETCORE_URLS: "http://+:7576"
      DATACENTER_ID: "30"
      MACHINE_ID: "30"
      REDIS_DB: "redis:6379"